### PR TITLE
Modified Ideas section to use attribute selectors

### PR DESCRIPTION
**Pull request by datencia**

### CODE REVIEW

**Review by brauliodiez — COMMENTED** [review]
If you feel in the mood feel free of updating as well the source code and love from idea to implementación.

**Comment by datencia** [comment]
ok! count on it!

**Comment by brauliodiez** [comment]
Great then I keep this PR open waiting for that update, thanks

**Comment by datencia** [comment]
TODO update README.md

**Comment by brauliodiez** [comment]
Good Stuff !! :) I'm going to merge it, later on if you want to update it you can just raise a new PR

**Pull request merged**
